export enum InventoryContainerEnum {
  Inventory = 'Inventory',
  Safe = 'Safe',
  Storage = 'Storage',
  Locker = 'Locker',
  Satchel = 'Satchel',
  Sack = 'Sack',
  Case = 'Case',
  Wardrobe = 'Wardrobe',
  Safe2 = 'Safe2',
  Wardrobe2 = 'Wardrobe2',
  Wardrobe3 = 'Wardrobe3',
  Wardrobe4 = 'Wardrobe4',
  Wardrobe5 = 'Wardrobe5',
  Wardrobe6 = 'Wardrobe6',
  Wardrobe7 = 'Wardrobe7',
  Wardrobe8 = 'Wardrobe8',
}
