version: '3.5'

services:
  ffxi-galaxy-frontend:
    build: ../../frontend
    image: ffxi-galaxy-frontend
    restart: always
    networks:
      - proxynet
      
  ffxi-galaxy-backend:
    build: ../../backend
    image: ffxi-galaxy-backend
    restart: always
    environment:
      PORT: 3000
      DATABASE_HOST: ffxi-galaxy-db
      DATABASE_PORT: 3306
      DATABASE_USER: admin
      DATABASE_PASSWORD: 12345
      DATABASE_NAME: ffxi-galaxy
    links: 
      - ohrbuehl-web-mysql-db
    depends_on:
      - ohrbuehl-web-mysql-db
    networks:
      - proxynet
      
  ffxi-galaxy-mysql-db:
    image: mysql:8.0.29
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 2beer4me@ffxi-galaxy
      MYSQL_DATABASE: ffxi-galaxy
      MYSQL_USER: admin
      MYSQL_PASSWORD: 12345
    volumes:
      - ../../data/db-data:/var/lib/mysql
    networks:
      - proxynet
      
networks:
  proxynet:
    name: webnet
